---
title: "Predict_Cell_Cycle_for_scRNA_seq"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Predict_Cell_Cycle_for_scRNA_seq}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r install}
devtools::install("F:/Genetic_Analysis_Learning/Plaisier_Lab_Projects/ccafv2_Rv2")
```


```{r running}

# can we get awasy


library(Seurat)
library("org.Hs.eg.db")
library(ccAFv2_Rv2)

# Load up U5 expression
U5_seurat = readRDS("F:/Genetic_Analysis_Learning/Plaisier_Lab_Projects/Data/U5/U5_normalized_ensembl.rds")

s.genes   = na.omit(unlist(mapIds(org.Hs.eg.db, keys = cc.genes$s.genes, keytype = "SYMBOL", column="ENSEMBL", multiVals='first')))
g2m.genes = na.omit(unlist(mapIds(org.Hs.eg.db, keys = cc.genes$g2m.genes, keytype = "SYMBOL", column="ENSEMBL", multiVals='first')))

# Seurat cell cycle scoring method
U5_seurat = CellCycleScoring(U5_seurat, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

# ccAFv2 cell cycle prediction method
U5_seurat = PredictCellCycle(U5_seurat)

```

```{r plotting}
library(grid)
library(gridExtra)

# Plot DimPlot of data
pdf('ccAFv2_U5_vignette1.pdf')
m1 = DimPlot(U5_seurat, group.by='Phase', reduction='umap')
m2 = DimPlot.ccAFv2(U5_seurat, reduction='umap')
lst1 = list(m1, m2)
grid.arrange(grobs = lst1, layout_matrix = rbind(c(1,NA), c(2,NA)), top = "")
dev.off()

```
